2023-08-27 13:43:13,614 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 13:43:26,682 django.request WARNING  Not Found: /
2023-08-27 15:00:11,237 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\users\models.py changed, reloading.
2023-08-27 15:00:18,148 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:02:39,782 django.utils.autoreload INFO     D:\Projects\django-microfinex\microfinex\settings\base.py changed, reloading.
2023-08-27 15:02:42,574 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:17:20,158 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\users\admin.py changed, reloading.
2023-08-27 15:17:22,565 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:26:49,613 django.utils.autoreload INFO     D:\Projects\django-microfinex\microfinex\urls.py changed, reloading.
2023-08-27 15:26:51,578 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:27:05,418 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:27:50,753 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:28:13,147 django.request WARNING  Not Found: /
2023-08-27 15:28:14,719 django.request WARNING  Not Found: /favicon.ico
2023-08-27 15:30:41,731 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\common\models.py changed, reloading.
2023-08-27 15:30:42,242 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\common\models.py changed, reloading.
2023-08-27 15:30:45,076 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:30:45,189 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:33:13,703 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\profiles\models.py changed, reloading.
2023-08-27 15:33:13,915 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\profiles\models.py changed, reloading.
2023-08-27 15:33:16,409 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:33:16,412 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:37:31,698 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\profiles\models.py changed, reloading.
2023-08-27 15:37:31,789 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\profiles\models.py changed, reloading.
2023-08-27 15:37:33,748 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:37:33,845 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:38:26,226 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\profiles\models.py changed, reloading.
2023-08-27 15:38:26,237 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\profiles\models.py changed, reloading.
2023-08-27 15:38:28,016 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:38:28,100 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:38:34,799 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\profiles\models.py changed, reloading.
2023-08-27 15:38:36,011 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\profiles\models.py changed, reloading.
2023-08-27 15:38:36,705 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:38:37,987 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:46:04,360 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\profiles\models.py changed, reloading.
2023-08-27 15:46:04,622 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\profiles\models.py changed, reloading.
2023-08-27 15:46:08,074 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:46:08,074 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:50:48,646 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\profiles\admin.py changed, reloading.
2023-08-27 15:50:48,647 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\profiles\admin.py changed, reloading.
2023-08-27 15:50:51,043 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:50:52,685 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:51:29,392 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\profiles\apps.py changed, reloading.
2023-08-27 15:51:29,875 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\profiles\apps.py changed, reloading.
2023-08-27 15:51:32,767 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:51:33,387 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-27 15:59:48,231 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-28 15:04:55,679 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-28 15:19:01,283 django.request ERROR    Internal Server Error: /api/v1/auth/users
Traceback (most recent call last):
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/api/v1/auth/users/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2023-08-28 15:19:54,307 django.request WARNING  Bad Request: /api/v1/auth/users/
2023-08-28 15:20:12,659 django.request ERROR    Internal Server Error: /api/v1/auth/users/
Traceback (most recent call last):
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\djoser\views.py", line 140, in perform_create
    settings.EMAIL.activation(self.request, context).send(to)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\templated_mail\mail.py", line 78, in send
    super(BaseEmailMessage, self).send(*args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\mail\message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\mail\message.py", line 255, in get_connection
    self.connection = get_connection(fail_silently=fail_silently)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\mail\__init__.py", line 50, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'djcelery_email'
2023-08-28 15:22:52,868 django.utils.autoreload INFO     D:\Projects\django-microfinex\microfinex\settings\development.py changed, reloading.
2023-08-28 15:22:58,605 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-28 15:23:06,051 django.request WARNING  Bad Request: /api/v1/auth/users/
2023-08-28 15:29:47,119 django.request ERROR    Internal Server Error: /api/v1/auth/users/activation
Traceback (most recent call last):
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/api/v1/auth/users/activation/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2023-08-28 15:52:41,382 django.request WARNING  Unauthorized: /api/v1/auth/jwt/create
2023-08-29 16:05:24,585 django.utils.autoreload INFO     D:\Projects\django-microfinex\microfinex\urls.py changed, reloading.
2023-08-29 16:05:29,690 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-29 16:10:31,197 django.request WARNING  Not Found: /api/v1/me
2023-08-29 16:10:50,179 django.request WARNING  Not Found: /api/v1/priofile/me/
2023-08-29 16:10:56,304 django.request WARNING  Not Found: /api/v1/priofile/me/
2023-08-29 17:52:42,721 django.utils.autoreload INFO     D:\Projects\django-microfinex\manage.py changed, reloading.
2023-08-29 17:52:45,997 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 09:42:04,760 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 09:42:14,707 django.request WARNING  Not Found: /
2023-08-31 09:42:15,390 django.request WARNING  Not Found: /favicon.ico
2023-08-31 09:45:22,625 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\loan_products\admin.py changed, reloading.
2023-08-31 09:45:24,686 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 09:46:03,314 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\currencies\admin.py changed, reloading.
2023-08-31 09:46:06,433 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 09:50:01,371 django.request ERROR    Internal Server Error: /supersecret/loans/loan/add/
Traceback (most recent call last):
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 1804, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 926, in log_addition
    object_repr=str(obj),
  File "D:\Projects\django-microfinex\apps\loans\models.py", line 33, in __str__
    return f"Loan for {self.user} - Amount: {self.loan_amount} {self.currency_id}"
AttributeError: 'Loan' object has no attribute 'user'
2023-08-31 10:03:20,982 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\loans\admin.py changed, reloading.
2023-08-31 10:03:25,902 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 10:03:34,073 django.request ERROR    Internal Server Error: /supersecret/loans/loan/add/
Traceback (most recent call last):
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 1804, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 926, in log_addition
    object_repr=str(obj),
  File "D:\Projects\django-microfinex\apps\loans\models.py", line 33, in __str__
    return f"Loan for {self.user} - Amount: {self.loan_amount} {self.currency_id}"
AttributeError: 'Loan' object has no attribute 'user'
2023-08-31 10:08:37,690 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\loans\models.py changed, reloading.
2023-08-31 10:08:41,504 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 10:18:45,139 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\loans\models.py changed, reloading.
2023-08-31 10:18:50,570 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 10:25:34,346 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\loans\admin.py changed, reloading.
2023-08-31 10:25:42,486 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 10:40:01,878 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\loans\models.py changed, reloading.
2023-08-31 10:40:07,624 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 10:40:27,820 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\loans\admin.py changed, reloading.
2023-08-31 10:40:29,673 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 10:47:38,881 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\loan_products\models.py changed, reloading.
2023-08-31 10:47:42,282 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 12:01:20,587 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 12:48:39,545 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\loans\urls.py changed, reloading.
2023-08-31 12:48:49,501 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 12:50:00,818 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\loans\views.py changed, reloading.
2023-08-31 12:50:04,781 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 12:53:55,726 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\loans\views.py changed, reloading.
2023-08-31 12:53:59,684 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 12:54:02,756 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\loans\views.py changed, reloading.
2023-08-31 12:54:04,367 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 12:54:09,138 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\loans\views.py changed, reloading.
2023-08-31 12:54:11,168 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 12:55:09,265 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\loans\urls.py changed, reloading.
2023-08-31 12:55:12,947 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 12:55:38,255 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\loans\urls.py changed, reloading.
2023-08-31 12:55:40,318 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 12:55:49,055 django.request WARNING  Unauthorized: /api/v1/loans/
2023-08-31 12:57:28,674 django.request WARNING  Unauthorized: /api/v1/auth/jwt/create
2023-08-31 12:57:44,885 django.request ERROR    Internal Server Error: /supersecret/loans/loan/1/change/
Traceback (most recent call last):
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 1855, in _changeform_view
    "subtitle": str(obj) if obj else None,
  File "D:\Projects\django-microfinex\apps\loans\models.py", line 33, in __str__
    return f"Loan for {self.client} - Amount: {self.loan_amount} {self.currency}"
AttributeError: 'Loan' object has no attribute 'loan_amount'
2023-08-31 12:57:48,448 django.request ERROR    Internal Server Error: /supersecret/loans/loan/1/change/
Traceback (most recent call last):
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 1855, in _changeform_view
    "subtitle": str(obj) if obj else None,
  File "D:\Projects\django-microfinex\apps\loans\models.py", line 33, in __str__
    return f"Loan for {self.client} - Amount: {self.loan_amount} {self.currency}"
AttributeError: 'Loan' object has no attribute 'loan_amount'
2023-08-31 12:57:53,291 django.request ERROR    Internal Server Error: /supersecret/loans/loan/1/change/
Traceback (most recent call last):
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 1855, in _changeform_view
    "subtitle": str(obj) if obj else None,
  File "D:\Projects\django-microfinex\apps\loans\models.py", line 33, in __str__
    return f"Loan for {self.client} - Amount: {self.loan_amount} {self.currency}"
AttributeError: 'Loan' object has no attribute 'loan_amount'
2023-08-31 13:56:55,351 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 14:04:04,580 django.request ERROR    Internal Server Error: /supersecret/clients/client/add/
Traceback (most recent call last):
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: clients_client

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 1070, in render
    return render_value_in_context(output, context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\template\base.py", line 1047, in render_value_in_context
    value = str(value)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\forms\boundfield.py", line 34, in __str__
    return self.as_widget()
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\forms\boundfield.py", line 107, in as_widget
    return widget.render(
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\forms\widgets.py", line 280, in render
    context = self.get_context(name, value, attrs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\widgets.py", line 320, in get_context
    "rendered_widget": self.widget.render(name, value, attrs),
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\forms\widgets.py", line 280, in render
    context = self.get_context(name, value, attrs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\forms\widgets.py", line 758, in get_context
    context = super().get_context(name, value, attrs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\forms\widgets.py", line 717, in get_context
    context["widget"]["optgroups"] = self.optgroups(
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\forms\widgets.py", line 657, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\forms\models.py", line 1403, in __iter__
    for obj in queryset:
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\db\models\query.py", line 516, in _iterator
    yield from iterable
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: clients_client
2023-08-31 14:40:44,312 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 14:43:48,938 django.request WARNING  Unauthorized: /api/v1/auth/jwt/create
2023-08-31 14:46:09,382 django.request ERROR    Internal Server Error: /supersecret/loans/loan/add/
Traceback (most recent call last):
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 1804, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\contrib\admin\options.py", line 926, in log_addition
    object_repr=str(obj),
  File "D:\Projects\django-microfinex\apps\loans\models.py", line 33, in __str__
    return f"Loan for {self.client} - Amount: {self.loan_amount} {self.currency}"
AttributeError: 'Loan' object has no attribute 'loan_amount'
2023-08-31 14:47:26,875 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\loans\models.py changed, reloading.
2023-08-31 14:47:29,416 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 14:56:10,135 django.utils.autoreload INFO     D:\Projects\django-microfinex\microfinex\urls.py changed, reloading.
2023-08-31 14:56:17,329 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 15:08:11,703 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-08-31 15:08:16,126 django.request ERROR    Internal Server Error: /api/v1/enquiries
Traceback (most recent call last):
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/api/v1/enquiries/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2023-08-31 15:08:38,891 django.utils.autoreload INFO     D:\Projects\django-microfinex\microfinex\urls.py changed, reloading.
2023-08-31 15:08:41,537 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 03:04:14,960 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 03:13:11,700 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 03:13:17,220 django.request WARNING  Not Found: /
2023-09-01 03:13:17,494 django.request WARNING  Not Found: /favicon.ico
2023-09-01 03:20:16,349 django.utils.autoreload INFO     /app/microfinex/settings/development.py changed, reloading.
2023-09-01 03:20:18,037 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 03:20:21,850 django.utils.autoreload INFO     /app/microfinex/settings/development.py changed, reloading.
2023-09-01 03:20:23,504 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 03:26:45,532 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 05:04:32,563 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 05:17:46,044 django.utils.autoreload INFO     /app/apps/profiles/models.py changed, reloading.
2023-09-01 05:17:47,966 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 06:00:51,605 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 06:04:01,417 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 06:10:04,610 django.request ERROR    Internal Server Error: /supersecret/users/user/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/models/options.py", line 681, in get_field
    return self.fields_map[field_name]
KeyError: 'client_loans_list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 272, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 303, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: User has no field named 'client_loans_list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 336, in result_list
    "results": list(results(cl)),
  File "/usr/local/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/usr/local/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 281, in lookup_field
    value = attr(obj)
  File "/app/apps/users/admin.py", line 80, in client_loans_list
    return obj.client_loans.count()
AttributeError: 'User' object has no attribute 'client_loans'
2023-09-01 06:14:28,571 django.utils.autoreload INFO     /app/apps/users/admin.py changed, reloading.
2023-09-01 06:14:30,340 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 08:15:04,821 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 08:21:54,013 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 08:33:06,277 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 08:37:00,022 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 08:45:01,718 django.utils.autoreload INFO     /app/microfinex/settings/development.py changed, reloading.
2023-09-01 08:45:03,959 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 08:45:39,735 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 08:45:42,828 django.utils.autoreload INFO     /app/microfinex/settings/development.py changed, reloading.
2023-09-01 08:45:44,713 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 09:02:20,099 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 09:21:02,518 flower.command INFO     Visit me at http://localhost:5555
2023-09-01 09:21:02,628 flower.command INFO     Broker: redis://redis:6379/0
2023-09-01 09:21:02,634 flower.command INFO     Registered tasks: 
['celery.accumulate',
 'celery.backend_cleanup',
 'celery.chain',
 'celery.chord',
 'celery.chord_unlock',
 'celery.chunks',
 'celery.group',
 'celery.map',
 'celery.starmap',
 'djcelery_email_send_multiple']
2023-09-01 09:21:02,663 kombu.mixins INFO     Connected to redis://redis:6379/0
2023-09-01 09:21:02,921 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 09:28:11,306 django.request WARNING  Unauthorized: /api/v1/enquiries
2023-09-01 09:30:43,505 django.utils.autoreload INFO     /app/microfinex/settings/development.py changed, reloading.
2023-09-01 09:30:45,595 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 09:33:24,719 django.utils.autoreload INFO     /app/microfinex/settings/development.py changed, reloading.
2023-09-01 09:33:26,577 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 09:33:31,511 django.utils.autoreload INFO     /app/microfinex/settings/development.py changed, reloading.
2023-09-01 09:33:33,445 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 09:35:54,146 django.utils.autoreload INFO     /app/microfinex/settings/development.py changed, reloading.
2023-09-01 09:35:56,020 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 09:39:47,319 flower.command INFO     Visit me at http://localhost:5555
2023-09-01 09:39:47,332 flower.command INFO     Broker: redis://redis:6379/0
2023-09-01 09:39:47,337 flower.command INFO     Registered tasks: 
['celery.accumulate',
 'celery.backend_cleanup',
 'celery.chain',
 'celery.chord',
 'celery.chord_unlock',
 'celery.chunks',
 'celery.group',
 'celery.map',
 'celery.starmap',
 'djcelery_email_send_multiple']
2023-09-01 09:39:47,356 kombu.mixins INFO     Connected to redis://redis:6379/0
2023-09-01 09:39:47,468 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 09:43:45,955 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 09:43:46,169 flower.command INFO     Visit me at http://localhost:5555
2023-09-01 09:43:46,183 flower.command INFO     Broker: redis://redis:6379/0
2023-09-01 09:43:46,187 flower.command INFO     Registered tasks: 
['celery.accumulate',
 'celery.backend_cleanup',
 'celery.chain',
 'celery.chord',
 'celery.chord_unlock',
 'celery.chunks',
 'celery.group',
 'celery.map',
 'celery.starmap',
 'djcelery_email_send_multiple']
2023-09-01 09:43:46,209 kombu.mixins INFO     Connected to redis://redis:6379/0
2023-09-01 09:44:37,544 django.request WARNING  Bad Request: /api/v1/auth/users/
2023-09-01 09:46:09,525 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 09:46:09,897 flower.command INFO     Visit me at http://localhost:5555
2023-09-01 09:46:09,910 flower.command INFO     Broker: redis://redis:6379/0
2023-09-01 09:46:09,913 flower.command INFO     Registered tasks: 
['celery.accumulate',
 'celery.backend_cleanup',
 'celery.chain',
 'celery.chord',
 'celery.chord_unlock',
 'celery.chunks',
 'celery.group',
 'celery.map',
 'celery.starmap',
 'djcelery_email_send_multiple']
2023-09-01 09:46:09,933 kombu.mixins INFO     Connected to redis://redis:6379/0
2023-09-01 09:53:36,642 django.security.csrf WARNING  Forbidden (Origin checking failed - http://localhost:8080 does not match any trusted origins.): /supersecret/login/
2023-09-01 13:33:01,051 flower.command INFO     Visit me at http://localhost:5555
2023-09-01 13:33:01,062 flower.command INFO     Broker: redis://redis:6379/0
2023-09-01 13:33:01,066 flower.command INFO     Registered tasks: 
['celery.accumulate',
 'celery.backend_cleanup',
 'celery.chain',
 'celery.chord',
 'celery.chord_unlock',
 'celery.chunks',
 'celery.group',
 'celery.map',
 'celery.starmap',
 'djcelery_email_send_multiple']
2023-09-01 13:33:01,065 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 13:33:01,091 kombu.mixins INFO     Connected to redis://redis:6379/0
2023-09-01 14:07:25,719 flower.command INFO     Visit me at http://localhost:5555
2023-09-01 14:07:25,798 flower.command INFO     Broker: redis://redis:6379/0
2023-09-01 14:07:25,817 flower.command INFO     Registered tasks: 
['celery.accumulate',
 'celery.backend_cleanup',
 'celery.chain',
 'celery.chord',
 'celery.chord_unlock',
 'celery.chunks',
 'celery.group',
 'celery.map',
 'celery.starmap',
 'djcelery_email_send_multiple']
2023-09-01 14:07:25,921 kombu.mixins INFO     Connected to redis://redis:6379/0
2023-09-01 14:07:30,754 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-01 14:20:19,987 flower.command INFO     Visit me at http://localhost:5555
2023-09-01 14:20:20,086 flower.command INFO     Broker: redis://redis:6379/0
2023-09-01 14:20:20,090 flower.command INFO     Registered tasks: 
['celery.accumulate',
 'celery.backend_cleanup',
 'celery.chain',
 'celery.chord',
 'celery.chord_unlock',
 'celery.chunks',
 'celery.group',
 'celery.map',
 'celery.starmap',
 'djcelery_email_send_multiple']
2023-09-01 14:20:20,136 kombu.mixins INFO     Connected to redis://redis:6379/0
2023-09-01 14:20:21,330 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-02 14:43:10,456 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-02 14:43:52,875 django.utils.autoreload INFO     D:\Projects\django-microfinex\microfinex\settings\development.py changed, reloading.
2023-09-02 14:43:53,958 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-02 14:46:41,108 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-02 14:50:10,444 django.request WARNING  Not Found: /api/v1/auth/jwt/create
2023-09-02 14:50:39,617 django.request WARNING  Not Found: /api/v1/auth/jwt/create
2023-09-02 14:51:48,128 django.utils.autoreload INFO     D:\Projects\django-microfinex\microfinex\urls.py changed, reloading.
2023-09-02 14:51:49,092 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-02 14:51:51,853 django.request ERROR    Internal Server Error: /api/v1/auth/jwt/create
Traceback (most recent call last):
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "D:\Projects\django-microfinex\.venv\lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/v1/auth/jwt/create/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2023-09-02 14:52:25,980 django.utils.autoreload INFO     D:\Projects\django-microfinex\apps\users\urls.py changed, reloading.
2023-09-02 14:52:27,044 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-02 14:52:30,372 django.request WARNING  Unauthorized: /api/v1/auth/jwt/create
2023-09-02 15:04:01,569 django.request WARNING  Bad Request: /api/v1/auth/users/
2023-09-02 15:14:41,756 django.request WARNING  Unauthorized: /api/v1/auth/logout
2023-09-02 15:15:21,298 django.utils.autoreload INFO     D:\Projects\django-microfinex\microfinex\settings\development.py changed, reloading.
2023-09-02 15:15:23,642 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-02 15:16:38,998 django.utils.autoreload INFO     D:\Projects\django-microfinex\microfinex\settings\development.py changed, reloading.
2023-09-02 15:16:39,961 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-10 02:04:06,829 flower.command INFO     Visit me at http://localhost:5555
2023-09-10 02:04:07,012 flower.command INFO     Broker: redis://redis:6379/0
2023-09-10 02:04:07,016 flower.command INFO     Registered tasks: 
['celery.accumulate',
 'celery.backend_cleanup',
 'celery.chain',
 'celery.chord',
 'celery.chord_unlock',
 'celery.chunks',
 'celery.group',
 'celery.map',
 'celery.starmap',
 'djcelery_email_send_multiple']
2023-09-10 02:04:07,038 kombu.mixins INFO     Connected to redis://redis:6379/0
2023-09-10 02:04:07,102 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-09-10 02:05:55,030 django.request WARNING  Not Found: /api/v1/users/
2023-09-10 02:42:14,974 django.request WARNING  Not Found: /api/v1/users
2023-09-10 02:43:07,307 django.request ERROR    Internal Server Error: /api/v1/auth/users
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost/api/v1/auth/users/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2023-11-09 07:33:02,575 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 07:34:47,685 django.utils.autoreload INFO     D:\Projects\Python\django-microfinex\microfinex\settings\development.py changed, reloading.
2023-11-09 07:34:48,615 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 07:37:18,439 django.utils.autoreload INFO     D:\Projects\Python\django-microfinex\microfinex\settings\development.py changed, reloading.
2023-11-09 07:37:19,678 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 07:37:35,045 django.utils.autoreload INFO     D:\Projects\Python\django-microfinex\microfinex\settings\development.py changed, reloading.
2023-11-09 07:37:37,480 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 07:41:26,532 django.request WARNING  Not Found: /
2023-11-09 07:42:51,851 django.request WARNING  Not Found: /favicon.ico
2023-11-09 07:43:43,609 django.request WARNING  Not Found: /api/v1/clients
2023-11-09 07:48:05,315 django.utils.autoreload INFO     D:\Projects\Python\django-microfinex\microfinex\urls.py changed, reloading.
2023-11-09 07:48:10,693 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 07:48:43,568 django.utils.autoreload INFO     D:\Projects\Python\django-microfinex\microfinex\urls.py changed, reloading.
2023-11-09 07:48:45,346 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 08:25:04,437 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 08:25:09,737 django.request WARNING  Unauthorized: /api/v1/loans/
2023-11-09 08:26:51,619 django.request WARNING  Unauthorized: /api/v1/auth/jwt/create
2023-11-09 08:28:16,064 django.request WARNING  Unauthorized: /api/v1/profile/me/
2023-11-09 08:28:42,261 django.request WARNING  Unauthorized: /api/v1/profile/me/
2023-11-09 08:28:44,771 django.request WARNING  Unauthorized: /api/v1/profile/me/
2023-11-09 08:29:30,956 django.request WARNING  Unauthorized: /api/v1/loans/
2023-11-09 12:20:24,586 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 12:47:34,101 django.request WARNING  Unauthorized: /api/v1/profile/me/
2023-11-09 12:48:46,566 django.request WARNING  Not Found: /api/v1/clients
2023-11-09 12:55:11,078 django.request WARNING  Not Found: /favicon.ico
2023-11-09 12:55:19,847 django.request WARNING  Not Found: /
2023-11-09 12:56:01,716 django.utils.autoreload INFO     D:\Projects\Python\django-microfinex\microfinex\urls.py changed, reloading.
2023-11-09 12:56:08,396 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 12:56:12,190 django.request WARNING  Not Found: /
2023-11-09 12:56:36,980 django.utils.autoreload INFO     D:\Projects\Python\django-microfinex\microfinex\urls.py changed, reloading.
2023-11-09 12:56:38,231 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 12:57:08,966 django.request WARNING  Not Found: /api/v1/clients/
2023-11-09 12:57:17,526 django.utils.autoreload INFO     D:\Projects\Python\django-microfinex\microfinex\urls.py changed, reloading.
2023-11-09 12:57:18,527 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 12:57:28,912 django.utils.autoreload INFO     D:\Projects\Python\django-microfinex\microfinex\urls.py changed, reloading.
2023-11-09 12:57:29,872 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 12:58:02,358 django.request WARNING  Not Found: /api/v1/clients/hdhd/kdkd
2023-11-09 12:58:26,889 django.request WARNING  Unauthorized: /api/v1/clients
2023-11-09 12:59:31,960 django.request WARNING  Unauthorized: /api/v1/clients
2023-11-09 13:01:08,662 django.utils.autoreload INFO     D:\Projects\Python\django-microfinex\apps\clients\views.py changed, reloading.
2023-11-09 13:01:11,713 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 13:01:33,097 django.request WARNING  Unauthorized: /api/v1/clients
2023-11-09 13:02:00,367 django.utils.autoreload INFO     D:\Projects\Python\django-microfinex\apps\clients\urls.py changed, reloading.
2023-11-09 13:02:01,462 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 13:02:01,996 django.request WARNING  Unauthorized: /api/v1/clients
2023-11-09 13:02:05,099 django.request WARNING  Unauthorized: /api/v1/clients
2023-11-09 13:02:06,926 django.request WARNING  Unauthorized: /api/v1/clients
2023-11-09 13:02:38,726 django.utils.autoreload INFO     D:\Projects\Python\django-microfinex\apps\clients\urls.py changed, reloading.
2023-11-09 13:02:39,555 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 13:03:03,050 django.utils.autoreload INFO     D:\Projects\Python\django-microfinex\apps\clients\views.py changed, reloading.
2023-11-09 13:03:04,060 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 13:06:08,374 django.utils.autoreload INFO     D:\Projects\Python\django-microfinex\apps\clients\urls.py changed, reloading.
2023-11-09 13:06:09,998 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 13:52:55,557 django.utils.autoreload INFO     D:\Projects\Python\django-microfinex\apps\clients\models.py changed, reloading.
2023-11-09 13:53:14,084 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 13:54:30,763 django.request WARNING  Bad Request: /api/v1/clients
2023-11-09 13:55:03,780 django.request ERROR    Internal Server Error: /api/v1/clients
Traceback (most recent call last):
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: table clients_client has no column named title

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\rest_framework\serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Projects\Python\django-microfinex\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: table clients_client has no column named title
2023-11-09 14:11:17,999 django.request WARNING  Unauthorized: /api/v1/clients
2023-11-09 15:26:24,395 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 15:28:18,805 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-11-09 15:30:54,373 django.request WARNING  Unauthorized: /api/v1/clients
